const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Behaviors.Pin,
		C3.Plugins.TextBox,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.TextBox.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Behaviors.lunarray_LiteTween.Acts.SetTarget,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.lunarray_LiteTween.Exps.Duration,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Arr.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{ID: 0},
	{IsOpen: 0},
	{Position: 0},
	{SaveX: 0},
	{SaveY: 0},
	{LiteTween: 0},
	{KartuMemory: 0},
	{MemoryBG: 0},
	{MemoryCardDeck: 0},
	{MemoryFramePool: 0},
	{MemoryIDs: 0},
	{MemoryKesulitanPermainan: 0},
	{ModalInputNama: 0},
	{ModalKalah: 0},
	{ModalMenang: 0},
	{Kawasan: 0},
	{NamaFoto: 0},
	{ArrayDrag: 0},
	{ArrayTemp: 0},
	{ArrayDrop: 0},
	{ArrayTemp2: 0},
	{ArrayPuzzleSets: 0},
	{ArrayChosenShuffled: 0},
	{ArrayChosenSet: 0},
	{Touch: 0},
	{Hitam: 0},
	{Pin: 0},
	{ButtonPopup: 0},
	{InputName: 0},
	{CardLevel: 0},
	{ButtonKembali: 0},
	{AJAX: 0},
	{JSON: 0},
	{ArrayRaw: 0},
	{ArraySorted: 0},
	{TextPrint: 0},
	{TextPrintName: 0},
	{HUD: 0},
	{TextPrintScore: 0},
	{TextID: 0},
	{Card_NameText: 0},
	{DropPictureWithName: 0},
	{MencocokkanLevel: 0},
	{DragID: 0},
	{DragDrop: 0},
	{Mencocokkan_Drag: 0},
	{PositionID: 0},
	{isFilled: 0},
	{DropID: 0},
	{Mencocokkan_Drop: 0},
	{BuildingNames: 0},
	{Array3Drag: 0},
	{Array2Selected: 0},
	{Array1Cards: 0},
	{KesulitanMencocokkangBG: 0},
	{KawasanText: 0},
	{SlotMengelompokkan: 0},
	{Rectangle: 0},
	{FrameID: 0},
	{Kelompok_Drag: 0},
	{Kelompok_Drop: 0},
	{MengelompokkanBG: 0},
	{MainPage: 0},
	{CardNamaKawasan: 0},
	{BGKawasan: 0},
	{CardMinigame: 0},
	{Text: 0},
	{Jigsaw_Drop: 0},
	{Jigsaw_Drag: 0},
	{PuzzleGame: 0},
	{ScoreVal: 0},
	{NameVal: 0},
	{IndexA: 0},
	{IsFirstCardOpened: 0},
	{FirstCard: 0},
	{MatchedCards: 0},
	{GameAktif: 0},
	{Touched: 0},
	{Data_Waktu: 0},
	{Data_Skor: 0},
	{PlayerName: 0},
	{TimeTaken: 0},
	{FinalScore: 0},
	{i: 0},
	{j: 0},
	{Temp: 0},
	{frameIndex: 0},
	{scoreA: 0},
	{scoreB: 0},
	{TempScore: 0},
	{TempName: 0},
	{Data_Waktu2: 0},
	{Data_Skor2: 0},
	{GameAktif2: 0},
	{TimeTaken2: 0},
	{MatchedCards2: 0},
	{FinalScore2: 0},
	{PlayerName2: 0},
	{IndexB: 0},
	{Kawasan2: 0},
	{Data_Waktu3: 0},
	{Data_Skor3: 0},
	{GameAktif3: 0},
	{TimeTaken3: 0},
	{MatchedCards3: 0},
	{FinalScore3: 0},
	{PlayerName3: 0},
	{tempCalc: 0},
	{Level: 0},
	{Variasi: 0},
	{Waktu: 0},
	{Data_Waktu4: 0},
	{TimeTaken4: 0},
	{GameAktif4: 0},
	{PuzzleSet: 0},
	{PlayerName4: 0},
	{FinalScore4: 0},
	{MatchedPuzzle: 0}
];

self.InstanceType = {
	KartuMemory: class extends self.ISpriteInstance {},
	MemoryBG: class extends self.ISpriteInstance {},
	MemoryCardDeck: class extends self.IArrayInstance {},
	MemoryFramePool: class extends self.IArrayInstance {},
	MemoryIDs: class extends self.IArrayInstance {},
	MemoryKesulitanPermainan: class extends self.ISpriteInstance {},
	ModalInputNama: class extends self.ISpriteInstance {},
	ModalKalah: class extends self.ISpriteInstance {},
	ModalMenang: class extends self.ISpriteInstance {},
	Kawasan: class extends self.IArrayInstance {},
	NamaFoto: class extends self.IArrayInstance {},
	ArrayDrag: class extends self.IArrayInstance {},
	ArrayTemp: class extends self.IArrayInstance {},
	ArrayDrop: class extends self.IArrayInstance {},
	ArrayTemp2: class extends self.IArrayInstance {},
	ArrayPuzzleSets: class extends self.IArrayInstance {},
	ArrayChosenShuffled: class extends self.IArrayInstance {},
	ArrayChosenSet: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	Hitam: class extends self.ISpriteInstance {},
	ButtonPopup: class extends self.ISpriteInstance {},
	InputName: class extends self.ITextInputInstance {},
	CardLevel: class extends self.ISpriteInstance {},
	ButtonKembali: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	ArrayRaw: class extends self.IArrayInstance {},
	ArraySorted: class extends self.IArrayInstance {},
	TextPrint: class extends self.ITextInstance {},
	TextPrintName: class extends self.ITextInstance {},
	HUD: class extends self.ITextInstance {},
	TextPrintScore: class extends self.ITextInstance {},
	Card_NameText: class extends self.ITextInstance {},
	DropPictureWithName: class extends self.ISpriteInstance {},
	MencocokkanLevel: class extends self.ISpriteInstance {},
	Mencocokkan_Drag: class extends self.ISpriteInstance {},
	Mencocokkan_Drop: class extends self.ISpriteInstance {},
	BuildingNames: class extends self.IArrayInstance {},
	Array3Drag: class extends self.IArrayInstance {},
	Array2Selected: class extends self.IArrayInstance {},
	Array1Cards: class extends self.IArrayInstance {},
	KesulitanMencocokkangBG: class extends self.ISpriteInstance {},
	KawasanText: class extends self.ITextInstance {},
	SlotMengelompokkan: class extends self.ISpriteInstance {},
	Rectangle: class extends self.ISpriteInstance {},
	Kelompok_Drag: class extends self.ISpriteInstance {},
	Kelompok_Drop: class extends self.ISpriteInstance {},
	MengelompokkanBG: class extends self.ISpriteInstance {},
	MainPage: class extends self.ISpriteInstance {},
	CardNamaKawasan: class extends self.ISpriteInstance {},
	BGKawasan: class extends self.ISpriteInstance {},
	CardMinigame: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Jigsaw_Drop: class extends self.ISpriteInstance {},
	Jigsaw_Drag: class extends self.ISpriteInstance {},
	PuzzleGame: class extends self.ISpriteInstance {}
}